version: '3.1'
services:
  sl:
    command: "-c 'config_file=/etc/postgresql/postgresql.conf'"
    image: postgres:12
    volumes:
      - /mnt/dsk/data-01/staging/postgres/slave:/var/lib/postgresql/data
      - ./postgres-slave.conf:/etc/postgresql/postgresql.conf
      - ./setup-node.sh:/docker-entrypoint-initdb.d/setup-node.sh
    restart: always
    ports:
      - 4001:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: rav
      PG_REP_USER: replicator
      PG_REP_PASSWORD: password
      PG_MASTER_HOST: 10.132.0.7
      PG_MASTER_PORT: 4000
      ROLE: slave

